### ISSUE TITLE
Size: Strip the Binary?

### ISSUE THREAD

**Issue by CodeMan99** [AnatoleLucet/docker-neovim#3]
I saw in #2 that there was a size conversation.

The size of `nvim` can be stipped to nearly half the size:

```
/ # wc -c /usr/local/bin/nvim
10742648 /usr/local/bin/nvim
/ # strip /usr/local/bin/nvim
/ # wc -c /usr/local/bin/nvim
5565640 /usr/local/bin/nvim
```

**Comment by AnatoleLucet** [comment]
I didn't even knew about strip! Looking nice on paper.
Is there any possible side effects?

**Comment by CodeMan99** [comment]
It removes debugging symbols. So in theory you'll get worse bug reports. In reality, every package manager (apt, pacman, yum) ships a stripped binary. That's why the packaged version of an app is almost always smaller than the manually compiled version.

**Comment by AnatoleLucet** [comment]
Great! Well, thank you for your feedback.
I've made the changes in the Dockerfiles (see https://github.com/AnatoleLucet/docker-neovim/commit/b3e24c296942e79dda9f8634ea391ba1182c0afa)

**Comment by CodeMan99** [comment]
Nice :+1: Thanks for the commit ref. I'm learning docker right now. Cool so see it was a matter of updating build dependencies and then calling `strip` as appropriate. :+1:
